### ISSUE TITLE
Users are sorted incorrectly

### ISSUE THREAD

**Issue by LoganSWarner** [afranka70/AbOutIssues#10]
# AbOut Version
326s17
# Submitted by
Mitchell Deplazes
# Description
On the **Administrator**/**Users** screen the list of users shown to administrators is sorted by the first letter of each user and not the last name.

**Comment by afranka70** [comment]
The text for user names should be the same as the text for student names. In #00 it is proposed that student names simply be a string of characters of some maximum length. Hence the only reasonable name sort would be by the lexical order of the strings composing these names.

**Comment by LoganSWarner** [comment]
Closing as not an issue.
