### ISSUE TITLE
Changes to Faculty tab Edit Assessment Form

### ISSUE THREAD

**Issue by afranka70** [afranka70/AbOutIssues#101]
# AbOut Version
AbOutPEv0.2

# Description
Closely following the Outcomes box should be 4  new expandable text boxes labeled:
Method
Unsatisfactory
Satisfactory
Exemplary

There should be a small vertical space between the 1st & 2nd performance item and the 2nd and 3rd Performance item.

In the Performance area there should be a:
<positive integer text box> Total
This should be vertically aligned with the current 3 performance items and separated by a larger vertical space. The <positive integer text box> should not be changeable by the user and should display a running sum of the 3 performance values.

At the bottom of the form  there should  not be a Delete button for  current users. 
The "Reset" button should be re-label "Cancel" and when clicked  should replace this form with the *Common Faculty Task* pane without making any changes to the database.
The "Save" button should become active when (1) a positive integer is entered for at least one performance value and (2) an entry is made in the "Based On" text box.

Performance values and "Based On' values can be  changed at any time prior to clicking "Save". When"Save" is clicked these four values are stored in the data base and the *Common Faculty Task* pane is displayed. When the *Common Faculty Task* pane is displayed, the assessment item can  be clicked and will display the current data base values which can edited and saved.

# Related issues
#100

**Comment by omar-alenezi** [comment]
The fixes in the pull request should confirm to this issue fix in the files: 
application/faculty/view/facultyAssessment.php
application/javascript/main.js
