### ISSUE TITLE
Restore +Outcomes to AbOut Main Screen

### ISSUE THREAD

**Issue by afranka70** [afranka70/AbOutIssues#105]
# AbOut Version
AbOutPEv0.2

# Description
Issue #81 was a mistake. Frank was thinking that Outcomes would be part of the database load. It makes more sense for the Outcomes to be entered by the administrator (we will create this role).

Restore +Outcomes to the main screen, but:
- fix Outcome Abbreviation to  EAC
- associated text box can contain any  4 character string (enlarge box)
- fix Program Abbreviation to SE
- delete "End Semester"
- add reset button that will just clear the two text boxes
- add Cancel button the will abort transaction and bring up the **Common Administrator Tasks** pane

# Related issues
#81

**Comment by omar-alenezi** [comment]
Will have to revert the changes i made for issue#81 and change what we already had to confirm with this.
