### ISSUE TITLE
Complete and extend issues # 87 and #95

### ISSUE THREAD

**Issue by afranka70** [afranka70/AbOutIssues#107]
# AbOut Version
AbOutPEv0.2

# Description
Issues #87 and #95 were not completed;
The **Import Students into an Offering** and associated text should be deleted.

Also, the first bullet in **Add a Course** and **Add a Course Offering** should be deleted.

# Related issues
#87
#95

**Comment by omar-alenezi** [comment]
It should be fixed already? its fixed in my project files anyway.

**Comment by omar-alenezi** [comment]
Oh you meant the common Administrator tasks pane. 
It is fixed now in 
admin/view/adminFaq.php
