### ISSUE TITLE
Javascript in main.js uses == instead of === in all cases

### ISSUE THREAD

**Issue by HumbleHominid** [afranka70/AbOutIssues#114]
# AbOut Version
0.3
# Description
Javascript in main.js uses == instead of === in all cases. Should be using === with casting if necessary.
# Related issues

**Comment by LoganSWarner** [comment]
I'm not sure this is a problem, as in many cases, it may be desirable to compare, for example whether two things are both "falsy", but I have not thoroughly reviewed the JS code, and did notice issues with it for what little time I looked at it.
It is probably in need of a thorough cleanup.

**Comment by HumbleHominid** [comment]
In general, I dislike using or seeing == as opposed to === because the comparator has issues. In most cases that I checked === should have been used over ==. In cases other than checking if both are false values you should almost never use ==.

**Comment by omar-alenezi** [comment]
=== and !== are strict comparison operators
So when you use the 3 equal signs mean "equality without type coercion". Using the triple equals, the values must be equal in type as well.
here are some examples to clear them up better: 
```
0 == false   // true
0 === false  // false, because they are of a different type
1 == "1"     // true, automatic type conversion for value only
1 === "1"    // false, because they are of a different type
null == undefined // true
null === undefined // false
'0' == false // true
'0' === false // false0 == false   // true
0 === false  // false, because they are of a different type
1 == "1"     // true, automatic type conversion for value only
1 === "1"    // false, because they are of a different type
null == undefined // true
null === undefined // false
'0' == false // true
'0' === false // false
```

**Comment by LoganSWarner** [comment]
I understand, but sometimes nonstrictness is desirable. and I think there should be allowances for non-strict equality in some cases.
