### ISSUE TITLE
Change C.O.R.E to CORE.

### ISSUE THREAD

**Issue by afranka70** [afranka70/AbOutIssues#115]
# AbOut Version
0.3

# Description
In Reports/Reports change "C.O.R.E." to CORE. Also in **Common Reports Tasks**. Also in **C.O.R.E. Report**

# Related issues

**Comment by LoganSWarner** [comment]
For anyone wanting to fix, make sure you get every instance of it. `git grep -n "C\.O\.R\.E\."` should find them as far as I know.
