### ISSUE TITLE
When a non-registered user attempts to login they are presented with the wrong page

### ISSUE THREAD

**Issue by GammaGames** [afranka70/AbOutIssues#13]
# AbOut Version
326s17
# Submitted by
@afranka70 
# Description
When a non-registered user attempts they are presented with the screen:
![1](https://cloud.githubusercontent.com/assets/7832163/22947343/e32027e2-f2b7-11e6-9020-a7f960fd2a0e.png)
This screen conveys false information. The user never logged in and thus cannot successfully logout.

**Comment by LoganSWarner** [comment]
Closing for temp fix, new issue will be comprehensive.
