### ISSUE TITLE
Heading needs to  show "Montana  Tech"

### ISSUE THREAD

**Issue by afranka70** [afranka70/AbOutIssues#154]
# AbOut Version
DevPEv0.2

# Description
Current heading:
![image](https://cloud.githubusercontent.com/assets/25726083/26757792/0da02b92-4886-11e7-87e7-5958734e6e37.png)

Below **AbOutPE** add:
Montana Tech
in while at 40% the size of the heading.

# Related issues

**Comment by kneumiller** [comment]
What color do you want the Montana Tech to be?

![image](https://cloud.githubusercontent.com/assets/25360260/26802718/d0cf69ce-49fe-11e7-9436-c5e6bdff79d7.png)

Here's what I have, but I can change it before doing a pull request if you have suggestions

**Comment by afranka70** [comment]
closed 6/27 w/o check
