### ISSUE TITLE
Redundant step on help for each tab

### ISSUE THREAD

**Issue by LoganSWarner** [afranka70/AbOutIssues#19]
# AbOut Version
326s17
# Description
The first bullet point in the on-page help for each tab (shown when the tab is initially clicked) says to go to the tab...but **the user is already there**.
This is about a 2-minute fix (removing one line from each of three files).

**Comment by afranka70** [comment]
Hi Logan,
Where possible, I'd like our anomalies to refer to a particular screen. One reason is that as anomalies are fixed I want the code that is involved in closing an anomaly to at least be made more readable. 
Frank

**Comment by LoganSWarner** [comment]
In that case, this should become a meta-issue for a set of anomalies.

**Comment by afranka70** [comment]
Hi Logan,
Meta-issues become another layer of complexity. After discussion with you it seems best to leave these changes to the "help" screen bundled.
Frank

**Comment by LoganSWarner** [comment]
Okay, reclosing the individual one and removing the sub-issues section from this one, then.
