### ISSUE TITLE
Switch from XHTML 1.0 to HTML5

### ISSUE THREAD

**Issue by LoganSWarner** [afranka70/AbOutIssues#2]
# AbOut Version
326s17
# Description
Update all HTML/PHP files to the HTML5 standard.
# Related issues
#3

**Comment by afranka70** [comment]
2017-04-10: Cannot duplicate this anomaly as described

**Comment by LoganSWarner** [comment]
@afranka70 the comment contains a timestamp, you don't need to say the date. Anyways, I closed the one you meant to, issue #4, months ago.

**Comment by Sisune** [comment]
I actually just realized that this really should be a milestone.

**Comment by LoganSWarner** [comment]
I'm not sure it should be, mostly because the one related issue isn't really a _sub_issue, but instead has this as a soft dependency.
Additionally, as far as it _feeling_ like a marker of progress, I think that would be somewhat deceptive, this is mostly changing doctypes and cleaning up anything that doesn't verify (likely not much) after doing so.
