### ISSUE TITLE
Course numbers need to allow a W at the end

### ISSUE THREAD

**Issue by LoganSWarner** [afranka70/AbOutIssues#22]
# AbOut Version
326s17
# Submitted by
@afranka70 
# Description
Course numbers currently only allow 3 or 4 digits, but should also allow 3 digits followed by a W.

**Comment by LoganSWarner** [comment]
It seems that the issue was incorrectly worded, I've corrected it to indicate that the problem is not with the number of digits allowed, but that a W at the end is not allowed.

**Comment by trevorlbrooks** [comment]
Issue was caused by line 311 in application/javascript/main.js. This was a regex validation on client side. No server side issues with database. Please verify and merge issue22 branch in private.

**Comment by GammaGames** [comment]
Should be fixed using HTML5 input pattern attribute instead of javascript, but was fixed using js in https://github.com/afranka70/AbOutPrivate/pull/17

**Comment by LoganSWarner** [comment]
As I noted on (here)[https://github.com/afranka70/AbOutPrivate/commit/5a6761e3280e7104d999040ed19a888de5166ff5], this isn't quite right, so it'll need to be redone properly.
Additionally, this needs to be done with HTML5 form validation.

**Comment by GammaGames** [comment]
https://github.com/afranka70/AbOutPrivate/pull/20/commits
Reference to related commits from the branch
