### ISSUE TITLE
"CS/SE" program is unnecessary on Overview Outcome Report

### ISSUE THREAD

**Issue by LoganSWarner** [afranka70/AbOutIssues#39]
# AbOut Version
326s17
# Submitted by
@afranka70 
# Description
On other screens the user can choose either the CS program or the SE program or both. Presumably choosing the CS/SE program will generate results for all CS Department students. Instead of a dropdown box this screen should use check boxes like the other screens.

**Comment by Shnuggles** [comment]
This program will eventually be ported over to be used by more departments, check boxes will not work when that time comes.

**Comment by LoganSWarner** [comment]
@Shnuggles agreed, and closing in favor of #64 (as we discussed this in class).
