### ISSUE TITLE
Cannot add course as new active user

### ISSUE THREAD

**Issue by LoganSWarner** [afranka70/AbOutIssues#4]
# AbOut Version
326s17
# Submitted by
Frank Ackerman
# Description

1. Logged in as a new activer user *htu* and went to add course
2. Filled out form as seen
![issue1filledout](https://cloud.githubusercontent.com/assets/11509783/22945569/f021f7dc-f2b1-11e6-844e-dbe11682560e.png)
3. Clicked save, got delete prompt
![issue1deleteprompt](https://cloud.githubusercontent.com/assets/11509783/22945568/ee7cbb24-f2b1-11e6-85b2-89154353e2d5.png)
4. Clicked ok, same prompt came up again and again
5. Clicked cancel, course was not added 

# Related issues

**Comment by LoganSWarner** [comment]
Addressed in unknown version

**Comment by afranka70** [comment]
Tried this again with AbOutPrivate. Worked.
