### ISSUE TITLE
Incorrect instructions for inactive users

### ISSUE THREAD

**Issue by LoganSWarner** [afranka70/AbOutIssues#42]
# AbOut Version
326s17
# Submitted by
@afranka70 
# Description
When an inactive user clicks the Faculty tab, they are presented with a blank Faculty tab pane but with the normal information pane. This is confusing. Two possible fixes: (1) when an inactive user clicks on the Faculty tab, they get a pop-up that these functions are not available to an inactive user, or (2) along with a blank Faulty pane, they get an information screen informing them that faculty functions are not available to an inactive user.

This issue taken from the manually created Anomaly  Report v1.1AAF01.

**Comment by LoganSWarner** [comment]
Original thing started with he/she, changed to she exclusively. he/she is acceptable, but singular they sounds better, is easier to type, is correct, and is easier to keep straight.

**Comment by LoganSWarner** [comment]
Closing in favor of #52

**Comment by afranka70** [comment]
Using a 4/17/17 version. This no longer appears to be the case.
