### ISSUE TITLE
Add Assessment Cancel and Reset button functinality

### ISSUE THREAD

**Issue by GammaGames** [afranka70/AbOutIssues#46]
# AbOut Version
326s17
# Submitted by
@afranka70 
# Description
As per #41, this screen should have a Cancel button and the Reset button should be moved to the right. When clicked, the Cancel button briefly displays the text "This assessment has been canceled" and then displays the Common Faculty Tasks panel but leaves the left panel as it was when this screen was requested. 

When an assessment is saved, a Delete button is added to the screen. This is confusing and not necessary. The function of this screen is to add an assessment. An assessment can be deleted via the Edit Assessment screen. 

# Related issues
#41

**Comment by LoganSWarner** [comment]
This doesn't add anything besides specify a screen (and we should have all reviewed for button consistency anyways), closing as duplicate.
