### ISSUE TITLE
Max assessment points

### ISSUE THREAD

**Issue by GammaGames** [afranka70/AbOutIssues#47]
# AbOut Version
326s17
# Submitted by
@afranka70 
# Description
Currently, assessment points is restrictive, but not in the right way.
It should:
- Allow a maximum of 1000 points
- Allow decimals with two digits after the decimal point
- Disallow negative points (can currently be entered via *e.g.* 1-99)
- Contain a placeholder to show the format expected
- Not allow submitting the form unless it is valid

# Related issues
#38 
#3 
#2

**Comment by LoganSWarner** [comment]
This is **easily** solved on the client side with HTML5 clientside form validation. The database also needs to disallow invalid entries.

**Comment by LoganSWarner** [comment]
I'm not sure why I removed the JavaScript label, and I believe this was one where we forgot to readd the HTML label.
