### ISSUE TITLE
Anomalous padding of forms inside dispForms

### ISSUE THREAD

**Issue by LoganSWarner** [afranka70/AbOutIssues#50]
# AbOut Version
326s17
# Description
The whole main block already has a significant border around it, it does not need bottom padding and such padding is not in the design.
Note that, whether we want top padding or not (probably not, I don't see a point to it), we want side padding to be the same; in CSS, this can be done with a shorthand of side then top+bottom, thus `0 10px`.

**Comment by ljstout** [comment]
Got your messages -- thanks, Zach & I should have it done today/tomorrow.

**Comment by LoganSWarner** [comment]
I've updated the issue title to prevent confusion; technically, this was a broader issue, but some of the details of what was were forgotten about. The other anomalous padding problems will be in a new issue.
