### ISSUE TITLE
Cannot load student O'Neil

### ISSUE THREAD

**Issue by afranka70** [afranka70/AbOutIssues#55]
# AbOut Version
AbOut326s17

# Description
When the student name in the file to be imported in **Administrator**/*Courses*/"Add Offering" and "Edit Offering" contains a quote mark, for example: Chris O’Neil
That student is silently omitted from the list of students.

# Related issues

**Comment by trevorlbrooks** [comment]
This may be fixed during #116. This may be related to the quote not being escaped in the database query. The fix for #116 moves statements to using bind values, which would escape the quote.
