### ISSUE TITLE
Redundant bullets in "Common Adminstrator Task" pane

### ISSUE THREAD

**Issue by afranka70** [afranka70/AbOutIssues#61]
# AbOut Version
326s17
# Submitted by
Frank Ackerman
# Description
As with other tabs, there is a redundant first bullet point (you're already here, you don't need to be told to go here).
![redundantbullet](https://cloud.githubusercontent.com/assets/11509783/22948263/092f820e-f2bb-11e6-9f75-a3718919a51b.png)

**Comment by LoganSWarner** [comment]
Duplicate of #19 (covers all these panes)

**Comment by LoganSWarner** [comment]
Reponed for separation of issues.
