### ISSUE TITLE
application/login/view/loginNotice.php contains no PHP.

### ISSUE THREAD

**Issue by afranka70** [afranka70/AbOutIssues#71]
# AbOut Version
326s17
# Description
This file should be renamed with an .html extension. That is easy to do. More  challenging is finding all the files in which this name is referenced. That can be done by issuing
% grep -r 'loginNotice.php' . 
in AbOut326s17LFM

It suggested that making these file name changes be coordinated with the five 326 teams and the three V&V people. They should only be done when no one has outstanding "push" requests and the repository has been sanity checked.

Ideally this type of change should be made in only one local repository and a system sanity test should be run before the changes are pushed to the main repository.

# Related issues

**Comment by Areid406** [comment]
Renamed file to html, reuploaded to dropbox, need to delete the .php copy.

**Comment by Areid406** [comment]
Named loginNotice.php to loginNotice.html in loginController.php

**Comment by Areid406** [comment]
Deleted loginNotice.php

**Comment by LoganSWarner** [comment]
Note that in the future, V&V should close issues.
