### ISSUE TITLE
Cannot have section 10 in offering

### ISSUE THREAD

**Issue by GammaGames** [afranka70/AbOutIssues#73]
# AbOut Version
326s17
# Description
Current behavior: In Add Offering, section numbers allowed are 01-09 and 11-19 (the least significant digit is not allowed to be 0)
Desired behavior: Section numbers allowed are 01-19
# Related Issues
#2 
#3

**Comment by LoganSWarner** [comment]
Note that this is because of an error in the JS that checks it, but that we do _not_ want to fix that JS, we want to _replace_ it.

**Comment by HumbleHominid** [comment]
Just to be clear, we want to have a section 10 as a valid input?

**Comment by LoganSWarner** [comment]
Yes, I'll add more information to the issue.

**Comment by HumbleHominid** [comment]
Let me know the response to this too so I can implement the fix.

**Comment by afranka70** [comment]
The issue clearly calls for have the full complement of section numbers (01 through 19), however, if having the full complement of section numbers is a big deal in the current scheme of things, it will be satisfactory for the foreseeable future to only have sections (01 through 09).

**Comment by LoganSWarner** [comment]
@afranka70 I believe now that 01-09 and 11-19 was correct. We use section numbers with a most significant digit of 1 for lab sections, and I believe 10 is skipped, which would mean this issue is invalid.
