### ISSUE TITLE
Outcome abbreviation doesn't properly validate

### ISSUE THREAD

**Issue by GammaGames** [afranka70/AbOutIssues#75]
# AbOut Version
326s17
# Description
Current behavior: Outcome abbreviations let you enter anything, saving only the first two characters
Desired behavior: Outcome abbreviations should only allow valid abbreviations according to ABET standards (three capital letters and up to five characters, separated by a space)
# Related Issues
#2 
#3

**Comment by LoganSWarner** [comment]
Note that we don't want to _fix_ the JS, but replace it with HTML5 field validation.

**Comment by trevorlbrooks** [comment]
Missing HTML5 issue label.

**Comment by HumbleHominid** [comment]
Just for clarification, is 2 the maximum that should be allowed as in input?

**Comment by LoganSWarner** [comment]
I believe that one is the maximum, and that it is always a lowercase letter, but I will need to ask Frank about that, he'll know where to find the ABET documents.

**Comment by HumbleHominid** [comment]
Please update this thread with a response so I can implement the fix.

**Comment by afranka70** [comment]
I don't know if there is an ABET standard for labeling individual outcomes. 

But for now we’ll go with the 2 pull down choices and accept up to five (5) characters (any) in in the text box. As soon as we can we’ll make setting the outcome list an Administrator only function so most users won’t need software support and the Administrators can work until they get the Outcomes list the way the department wants it. It will tend to stay the same from semester to semester.
