### ISSUE TITLE
Version number should be displayed.

### ISSUE THREAD

**Issue by afranka70** [afranka70/AbOutIssues#78]
# AbOut Version
326s17
# Description
The version number should be accessible from the UI. An easy way to do this is to have this number appear in the lower left of the "Welcome" panel on the home page: "Version: xxxxxxxxxxxxxxx"  flush with the right edge of panel. No constraints on the string giving the version number except the whole phrase should be in **black** text and  fit comfortable at the end of the "*Best if used ..." white line.

# Related issues
none

**Comment by LoganSWarner** [comment]
I think version number could be at the top of every page in the top left corner. Users may want to know the version outside of the welcome screen, and we aren't really using that space.

**Comment by HumbleHominid** [comment]
this needs to be closed. as it was merged as per here afranka70/AbOutPrivate/pull/29
