### ISSUE TITLE
Modify front screen for AbOutPE

### ISSUE THREAD

**Issue by afranka70** [afranka70/AbOutIssues#87]
# AbOut Version
AbOutPE

# Description
In AbOut Front Screen
- change AbOut heading to AbOutPE
- remove the Inport Students into an Offering heading and text.

# Related issues
#107

**Comment by omar-alenezi** [comment]
Changed AbOut header in AbOutPE/includes/header.php to display AbOutPE instead of the AbOut

**Comment by omar-alenezi** [comment]
AbOutPE/application/admin/view/adminOffering.php
AbOutPE/application/faculty/view/facultyOffering.php
both has to import student into the offering that needs to be changed

**Comment by omar-alenezi** [comment]
This issue have been fixed
