### ISSUE TITLE
Changes to Add Course Form

### ISSUE THREAD

**Issue by afranka70** [afranka70/AbOutIssues#88]
# AbOut Version
AbOutPE

# Description
- Current Adminstrator/Add Course:
![image](https://cloud.githubusercontent.com/assets/25726083/24872860/17c932d2-1ddc-11e7-841b-b521e8d1abc9.png)

Changes:
Make *Course Abbreviation: a fixed field containing ESOF.
Eliminate CS/SE check boxes and fix at checked SE
Remove OutComes heading

# Related issues
#103

**Comment by omar-alenezi** [comment]
Fixed! in the 
AbOutPE/application/admin/view/adminCourse.php 
took out the sections that displays more than one options of course abbreviations and program to be only: 
ESOF - abbreviation 
SE - Program
