### ISSUE TITLE
Admin cannot edit user roles

### ISSUE THREAD

**Issue by LoganSWarner** [afranka70/AbOutIssues#9]
# AbOut Version
326s17
# Submitted by
Mitchell Deplazes
# Description
The administrator is unable to edit user roles since users are granted all roles.
# Related Issues
#8

**Comment by afranka70** [comment]
This issue is misleading. As currently implemented, there are only two types of users: active and inactive. Either type is able to change any of the values on the "Administrator"/"Edit User" screen.

**Comment by LoganSWarner** [comment]
For the time being, I'm closing this as a duplicate of #8 (may reopen if 8 is approved).
