### ISSUE TITLE
On Administrator Add Offering and Edit Offering Form drop Students and associated material

### ISSUE THREAD

**Issue by afranka70** [afranka70/AbOutIssues#91]
# AbOut Version
AbOutPE

# Description
In *Administrator/Edit Offering Form*:
![image](https://cloud.githubusercontent.com/assets/25726083/24873679/024a5c12-1ddf-11e7-942f-7c1a95712987.png)
 
**Delete**  "Students" and associated material.

# Related issues

**Comment by omar-alenezi** [comment]
Fixed with issue #87

**Comment by afranka70** [comment]
Closing on PEv0.1 but see issues 126,127, 128
