### ISSUE TITLE
Modify Add Assessment Screen for PE

### ISSUE THREAD

**Issue by afranka70** [afranka70/AbOutIssues#92]
# AbOut Version
AbOutPE

# Description
Current Faculty/Add Assessment:
![image](https://cloud.githubusercontent.com/assets/25726083/24874160/e5669dca-1de0-11e7-824f-a157449e13af.png)

 •	Extend *Assessment Description* box to end of *Outcomes* box
•	Remove Maximum points
•	“Scores” -> “Performance
•	Scores for 3 levels and Sum:
        <up to 3-digit numeric box> Unsatisfactory
        <up to 3-digit numeric box> Satisfactory
        <up to 3-digit numeric box> Exemplary

        <up to 3-digit numeric box> Sum
        

# Related issues

**Comment by omar-alenezi** [comment]
Fixed the issue of the incorrect view displaying in
AbOutPE/application/faculty/view/facultyAssessment.php

**Comment by afranka70** [comment]
Closing on v0.1 but see 126
