### ISSUE TITLE
On Reports tab only one report

### ISSUE THREAD

**Issue by afranka70** [afranka70/AbOutIssues#94]
# AbOut Version
AbOutPE

# Description
 esof326s17 *Reports* tab:
![image](https://cloud.githubusercontent.com/assets/25726083/24874721/e4f28640-1de2-11e7-9e01-c441aea3d692.png)

"Change Overview Outcome Report" to "Outcomes Report" but clicking it just brings up initial *Reports* screen.

Delete other 4 reports.

On information  pane change "Common Reports Tasks" to "Reports Task":
- Click on the "Outcomes Report" link
- Click on the Single Semester or a Start and End Semester
- Note: Single semester will be blank if you select Start and End Semesters

Delete "View a C.O.R.E Report" and associated bullets
Delete "View a Matrix Report" and associated bullets

# Related issues

**Comment by omar-alenezi** [comment]
Fixed in application/reports/view/reportTree.php
and   in application/reports/ReportsREST.php
issue is done

**Comment by omar-alenezi** [comment]
Fixed in reports reports/view/reportFaq.php 
I had the wrong fix on a different file now its reverted and fixed properly
