### ISSUE TITLE
AbOut Front Screen should specify just Firefox 

### ISSUE THREAD

**Issue by afranka70** [afranka70/AbOutIssues#95]
# AbOut Version
326s17

# Description
Remove "Chrome," and "or Internet Explorer"

# Related issues

**Comment by LoganSWarner** [comment]
Please note that if this is forcing out people by browser, it would need JavaScript. I'm pretty sure we want to support Chrome as well, just not have automated testing for it.

**Comment by omar-alenezi** [comment]
Fixed in application/login/loginWelcome.php
