### ISSUE TITLE
Outcome descriptions need to start larger

### ISSUE THREAD

**Issue by afranka70** [afranka70/AbOutIssues#96]
# AbOut Version
326s17
# Description
The Outcomes box needs to be larger to accommodate larger outcome descriptions (such as those for AbOutPE)

**Comment by omar-alenezi** [comment]
He meant the Description box in the edit outcome page its two rows and 8 columns I think this will not work and need to be changed like what frank described. There's the same problem in the AbOutPE too but Frank didn't set it to an issue yet.

**Comment by omar-alenezi** [comment]
Fixed! waiting to validate

**Comment by LoganSWarner** [comment]
Flagging as anomaly because such narrow limits were not in the design (and this could cause issues with data that is valid/expected).

**Comment by omar-alenezi** [comment]
Redone the files and pull request I hope it confirms to your needs now.

**Comment by LoganSWarner** [comment]
Reopening since the fix isn't actually merged yet.

**Comment by LoganSWarner** [comment]
Splitting out the AbOutPE stuff to a separate issue, as only the main part of it was done with the pull request.

**Comment by LoganSWarner** [comment]
The fix was incomplete, actually.
